### ISSUE TITLE
Typo in aggregator?

### ISSUE THREAD

**Issue by melisandeteng** [hugobaudchon/geodataset#80]
https://github.com/hugobaudchon/geodataset/blob/a8616e9f1b10279f6f081e2910a192699c48fc78/geodataset/aggregator/aggregator.py#L97

Should this be    scores[score_name] = annotation[score_name] ?

**Comment by hugobaudchon** [comment]
Hi @melisandeteng, yes you're right! Thanks for catching this typo. It'll be fixed in the next version v0.1.3
